{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "novasignal.fullname" . }}
  labels:
    {{- include "novasignal.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    {{- include "novasignal.ingress.tls" . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          # API routes to backend
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "novasignal.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: {{ include "novasignal.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: {{ include "novasignal.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: {{ include "novasignal.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          # All other routes to frontend
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "novasignal.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}