{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "novasignal.fullname" . }}-secrets
  labels:
    {{- include "novasignal.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc }}
  {{- end }}
  {{- if .Values.secrets.redisPassword }}
  redis-password: {{ .Values.secrets.redisPassword | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc }}
  {{- end }}
  {{- if .Values.secrets.apiKeys }}
  {{- range $key, $value := .Values.secrets.apiKeys }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
  {{- if .Values.secrets.encryptionKey }}
  encryption-key: {{ .Values.secrets.encryptionKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.sessionSecret }}
  session-secret: {{ .Values.secrets.sessionSecret | b64enc }}
  {{- end }}
  {{- if .Values.secrets.webhookSecret }}
  webhook-secret: {{ .Values.secrets.webhookSecret | b64enc }}
  {{- end }}
{{- end }}
---
{{- if .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  labels:
    {{- include "novasignal.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.clusterIssuer | default "letsencrypt-prod" }}
type: kubernetes.io/tls
data:
  {{- if .Values.ingress.tls.crt }}
  tls.crt: {{ .Values.ingress.tls.crt | b64enc }}
  {{- end }}
  {{- if .Values.ingress.tls.key }}
  tls.key: {{ .Values.ingress.tls.key | b64enc }}
  {{- end }}
{{- end }}