# Frontend Service
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "novasignal.fullname" . }}-frontend
  labels:
    {{- include "novasignal.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "novasignal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
---
# Backend Service
{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "novasignal.fullname" . }}-backend
  labels:
    {{- include "novasignal.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "novasignal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}