name: Prevent Path Overlap
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  path-lock:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Check overlap with other open PRs
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const current = context.payload.pull_request.number;
            async function filesOf(prNumber) {
              const files = await github.paginate(github.rest.pulls.listFiles, {
                owner, repo, pull_number: prNumber, per_page: 100
              });
              return files.map(f => f.filename);
            }
            const currentFiles = new Set(await filesOf(current));
            const openPRs = await github.paginate(github.rest.pulls.list, {
              owner, repo, state: 'open', per_page: 100
            });
            const overlaps = [];
            for (const pr of openPRs) {
              if (pr.number === current || pr.draft) continue;
              const otherFiles = await filesOf(pr.number);
              const shared = otherFiles.filter(f => currentFiles.has(f));
              if (shared.length) overlaps.push({num: pr.number, title: pr.title, shared});
            }
            if (overlaps.length) {
              const msg = overlaps.map(o => `- PR #${o.num} "${o.title}"\n  Overlap: ${o.shared.slice(0,20).join(', ')}`).join('\n');
              core.setFailed(`This PR overlaps files modified by other open PRs:\n${msg}\n\nCoordinate ownership or retarget to a shared feature branch.`);
            } else {
              core.info('No overlapping files with other open PRs.');
            }